In [1]:
import numpy as np

Creating a Matrix using numpy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [6]:
matrix_2.shape

(3, 3)

Creating Matrices with Random values

In [7]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.12886599 0.77809194 0.85413611]
 [0.82272955 0.70855246 0.03674446]
 [0.83090873 0.18731196 0.19579848]]


Creating Matrices with random integers.

In [9]:
random_integer_matrix = np.random.randint(100,size=(4,5)) 
print(random_integer_matrix)

[[75 98 11 53 51]
 [92 12 58 64  1]
 [96 36 29 96  9]
 [13 21 66 10 49]]


Matrix with all the values as 1.

In [ ]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


Identity matrix

In [13]:
identity_matrix = np.eye(8)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
