In [1]:
''' 
1D = vectors
2D = matrix
3D,4D... = Tensors
FUNCTIONS IN NUMPY:
'''
import numpy as np

In [2]:
# 1. Arange
m = np.arange(10)
print(m)
m1 = np.arange(1,30,2)
print(m1)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [3]:
# 2. Linspace: it genrates no b/w two numbers in equi distance.
a = np.linspace(1,10,5) # 1:start,10:end,5:how many no we wants
print(a)
# To remove end point.
a = np.linspace(1,10,5,endpoint=False)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]
[1.  2.8 4.6 6.4 8.2]


In [4]:
# Reshape: it is used to change the shape of array.
b = np.arange(1,11)
b = b.reshape(5,2) # 5:row,2:column
print(b)
c = np.arange(1,31)
c = c.reshape(5,-1) # -1 means it will automatically calculate the number of columns.
print(c)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [9]:
# Slicing: it is used to get the part of array.
d = np.arange(1,11)
print(d[2:5]) # 2:5 means it will get the no from index 2 to 4.
print(d[:5]) # it will get the no from index 0 to 4.
m = np.arange(1,21).reshape(4,5)
print(m)
m[2:4, 1:4]

[3 4 5]
[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[12, 13, 14],
       [17, 18, 19]])