In [5]:
import numpy as np
a = np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [8]:
# Mask: A mask is a boolean array that can be used to select elements from another array.
#       -It is created by applying a condition to an array, which results in an array of the same shape containing True for elements that
#           satisfy the condition and False for those that do not.

mask = a >= 5
print(mask)
print(a[mask]) # it will print the numbers from the array a that are greater than or equal to 5.
mask = a%2 == 0
print(mask)
print(a[mask]) # it will print the even numbers from the array a.

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
[ 2  4  6  8 10 12 14 16 18 20]
