In [3]:
import numpy as np
import math
m = np.arange(1,21).reshape(4,5)
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
# vectorization is the process of applying a function to an entire array, rather than applying it to each element individually.
# - This can be done using the np.vectorize() function, which takes a function as an argument and returns a new function that can be 
#       applied to arrays.


vecfun = np.vectorize(math.sqrt) # it will apply the sqrt function to each element of the array m.
print(vecfun(m))
vecfun = np.vectorize(math.sin) # it will apply the sin function to each element of the array m.
print(vecfun(m))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]
 [4.         4.12310563 4.24264069 4.35889894 4.47213595]]
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
 [-0.99999021 -0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721  0.91294525]]


In [7]:
def myfunc(a, b):
    "Return a-b if a > b, and a+b otherwise."
    if a > b:
        return a - b
    else:
        return a + b

In [10]:
m2 = np.array([1,2,3,4])
vfunc = np.vectorize(myfunc)
print(vfunc(m2,2)) # it will apply the myfunc function to each element of the array m2, with 2 as the second argument.

[3 4 1 2]
