In [15]:
'''
STACKING: Stacking is the process of combining multiple arrays into a single array. 
   -This can be done using the np.stack() function, which takes a sequence of arrays and an axis as arguments and returns a 
       new array that is the result of stacking the input arrays along the specified axis.
       '''
import numpy as np
A = np.arange(1,5).reshape(2,2)
B = np.arange(11,19).reshape(2,4)
print(A)
print(B.T)


[[1 2]
 [3 4]]
[[11 15]
 [12 16]
 [13 17]
 [14 18]]


In [14]:
np.hstack((A,B)) # it will stack the arrays A and B horizontally (column-wise). so the number of rows should be same in both the arrays.

array([[ 1,  2, 11, 12, 13, 14],
       [ 3,  4, 15, 16, 17, 18]])

In [12]:
np.vstack((A,B.T)) # it will stack the arrays A and B vertically (row-wise). so the number of columns should be same in both the arrays.

array([[ 1,  2],
       [ 3,  4],
       [11, 15],
       [12, 16],
       [13, 17],
       [14, 18]])