In [1]:
import numpy as np
p = np.ones((3,3))
print(p)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2]:
p = np.zeros((3,3))
print(p)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
p = np.eye(5)
print(p)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
p = np.ones(5)
print(p)

[1. 1. 1. 1. 1.]


In [6]:
p = np.zeros(5)
print(p)

[0. 0. 0. 0. 0.]
