In [2]:
import numpy as np
Arr1 = np.arange(1, 10).reshape(3, 3)
Arr2 = np.arange(1,4)
print(Arr1)
print(Arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [3]:
print(Arr1*Arr2)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
